### ISSUE TITLE
Add information about licensing

### ISSUE THREAD

**Issue by vbauer** [macroday/AppCrashTracker#1]

**Comment by macroday** [comment]
Dear Vladislav,

I have updated about information of licensing. Please check it now.

On Mon, Jan 4, 2016 at 10:48 PM, Vladislav Bauer notifications@github.com
wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/macroday/AppCrashTracker/issues/1.

##

**Comment by vbauer** [comment]
Thank you for information.
