### ISSUE TITLE
More useful Informations

### ISSUE THREAD

**Issue by thedarkside** [macroday/AppCrashTracker#3]
Hi,
the project looks promising! I wonder if you want add some more useful information?
- orientation the device being hold
- ui orientation (not necessary the same as device orientation!)
- battery state in percent
- ram usage of this app
- free ram left
- diskspace (i know, its not easy because of multiple cards etc)
- rooted (yes/no)
- network state

Networkstate would be a nice feature cause there is sometimes no internet or a user is running my app in plane-mode and it crashes. The crash would be logged/queued on the device and sent when the app launches the next time with internetconnection. In this case its a good information whether there was a networkconnection during the crash or not.

What do you think?

**Comment by macroday** [comment]
Yeah, this information is nice. It will be added in few days. The offline crashed concept is pretty. It will also update in upcoming days.

**Comment by macroday** [comment]
Hi,

Please check now. Everything is updated.
